shipment_info_query = """     
        SELECT COLIS.PoidsPlein AS WEIGHT, 
        FICHE_LIVRAISON.LivNom AS NAME1,
        FICHE_LIVRAISON.Adresse1 AS ADDRESS1,
        FICHE_LIVRAISON.Adresse2 AS ADDRESS2,
        FICHE_LIVRAISON.Adresse3 AS ADDRESS3,
        FICHE_LIVRAISON.LivCodePostal AS ZIPCODE,
        FICHE_LIVRAISON.LivVille AS CITY,
        PAYS.CodePays AS COUNTRYCODE,
        FICHE_LIVRAISON.LivEMail AS EMAIL, 
        FICHE_LIVRAISON.LivMobile AS MOBILEPHONE,
        FICHE_LIVRAISON.LivTelephone AS PHONE
        FROM COLIS
    INNER JOIN DOSSIER ON COLIS.IDDossier = DOSSIER.IDDossier
    INNER JOIN FICHE ON DOSSIER.IDFiche = FICHE.IDFiche
    INNER JOIN
  (
      SELECT IDFicheLivraison, LivNom, LivCodePostal, LivVille, LivPays, LivEMail, LivMobile, LivTelephone, LivIDZonePays
          , Adresse1 = CASE WHEN [VUE:FICHE_LIVRAISON].livAdresse1 <> '' THEN [VUE:FICHE_LIVRAISON].LivAdresse1 ELSE CASE WHEN [VUE:FICHE_LIVRAISON].LivAdresse2 <> '' THEN [VUE:FICHE_LIVRAISON].LivAdresse2 ELSE [VUE:FICHE_LIVRAISON].LivAdresse3 END END
          , Adresse2 = CASE WHEN [VUE:FICHE_LIVRAISON].LivAdresse2 <> '' THEN [VUE:FICHE_LIVRAISON].LivAdresse2 ELSE [VUE:FICHE_LIVRAISON].LivAdresse3 END
          , Adresse3 = CASE WHEN [VUE:FICHE_LIVRAISON].LivAdresse2 <> '' AND [VUE:FICHE_LIVRAISON].LivAdresse3 <> '' THEN [VUE:FICHE_LIVRAISON].LivAdresse3 ELSE [VUE:FICHE_LIVRAISON].LivAdresse0Appartement END
      FROM [VUE:FICHE_LIVRAISON]
  ) FICHE_LIVRAISON ON DOSSIER.IdFicheLivraison = FICHE_LIVRAISON.IDFicheLivraison
  INNER JOIN FICHE LIV ON FICHE_LIVRAISON.IDFicheLivraison = LIV.IDFiche
  INNER JOIN TYPE_FICHE ON LIV.IDTypeFiche = TYPE_FICHE.IDTypeFiche
    INNER JOIN ZONE_PAYS ON FICHE_LIVRAISON.LivIDZonePays = ZONE_PAYS.IDZonePays
    INNER JOIN PAYS ON ZONE_PAYS.IDPays = PAYS.IDPays
    INNER JOIN DOSSIER_TRANSPORT ON DOSSIER.IDDossier = DOSSIER_TRANSPORT.IDDossier
    INNER JOIN TRANSPORT_PRODUIT ON DOSSIER_TRANSPORT.IDTransportProduit = TRANSPORT_PRODUIT.IDTransportProduit
WHERE COLIS.IDColis = ?
    AND TRANSPORT_PRODUIT.KeyEtiquette = 'GLS'
"""
